# Generated by Django 4.0.1 on 2022-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=models.CharField(choices=[('size', 'MB'), ('weight', 'kg'), ('dimentions', 'length')], max_length=200),
        ),
    ]
